test a animation for the logo + fix the text
The-Fltaushnt-Crew/roshbet pull request #13
Opened 2023-01-18 16:32 UTC by Shaktas

- test a spinning R logo with gradient border and background
- fix text too close to the banner

look at it and if you like it give me a 👍 ^^

2023-01-20 10:45 UTC, bfresnel requested changes
Code relu, j'ai 2 remarques. De plus, n'oublie pas de formatter le fichier CSS pour que tous se replace correctement. J'ai vu qu'il y avait une propriété qui se baladait

2023-01-20 10:45 UTC, bfresnel commented on style/style.css
> +    margin-left: 2%;
A quoi sert cette marge de 2%?

2023-01-20 10:45 UTC, bfresnel commented on style/style.css
> +    margin-top: -100px;
Je ne suis pas fan des margin négative. C'était le seul moyen de placer ta pièce au bon endroit ?

2023-01-20 13:05 UTC, Shaktas commented on style/style.css
> +    margin-left: 2%;
la margin est la pour decoler le texte de la baniere 
- image sans le margin
![image](https://user-images.githubusercontent.com/87345806/213701186-1decaa83-0d9f-4f97-b7e9-c9415a920e74.png)

2023-01-20 13:52 UTC, Shaktas commented on style/style.css
> +    margin-top: -100px;
alors pour le coup oui y une meilleur facon de faire avec 'position' je pense ^^

2023-01-21 14:46 UTC, bfresnel commented on style/style.css
> +    margin-top: -100px;
OK merci de l'info, y a possibilité que tu essaies d'implémenter ce position ? Ou ça fait tout péter ?

2023-01-22 11:12 UTC, Shaktas commented on style/style.css
> +    margin-top: -100px;
Je peut l'implementer sans que ca casse tout par contre le fichier .css qui tu as "ranger" va etre en "bordel" de nouveau par rapport a main

2023-01-22 21:48 UTC, bfresnel commented on style/style.css
> +    margin-top: -100px;
J'ai updaté la branche. Tout est à jour, finalement je valide le changement

2023-01-22 21:48 UTC, bfresnel approved these changes
Z'est parti

2023-01-22 21:49 UTC, merged